name: Kibot ERC/DRC

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: INTI-CMNB/KiBot@v2_k7
      with:
        config: kibot_test.yml
        schema: 'kicad/riotee-probe.kicad_sch'
        board: 'kicad/riotee-probe.kicad_pcb'
